/**
 * @file config/categories.ts
 * @description Premium fashion & lifestyle categories with Unsplash imagery.
 */

export interface Category {
  id: string;
  title: string;
  handle: string;
  image: string;
  emoji: string;
  description: string;
  color: string;
  department: string;
}

const U = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=400&h=400&fit=crop&auto=format&q=80`;

export const CATEGORIES: Category[] = [
  // ── Women's Fashion ─────────────────────────────────────────────────────────
  {
    id: 'womens-dresses',
    title: 'Dresses',
    handle: 'dresses',
    image: U('1515886657613-9f3515b0c78f'),
    emoji: '👗',
    description: 'Elegant silhouettes for every occasion',
    color: 'bg-rose-50',
    department: "Women's Fashion",
  },
  {
    id: 'womens-tops',
    title: 'Tops & Blouses',
    handle: 'tops',
    image: U('1544441893-675173e2b2e4'),
    emoji: '👚',
    description: 'Curated tops for the modern woman',
    color: 'bg-pink-50',
    department: "Women's Fashion",
  },
  {
    id: 'sarees',
    title: 'Sarees',
    handle: 'sarees',
    image: U('1610030469983-98e550d6193c'),
    emoji: '🥻',
    description: 'Timeless Indian heritage in silk',
    color: 'bg-amber-50',
    department: "Women's Fashion",
  },
  {
    id: 'kurtas-women',
    title: 'Kurtas',
    handle: 'kurtas-women',
    image: U('1583391265880-6a8a40b5e375'),
    emoji: '🥻',
    description: 'Handcrafted ethnic elegance',
    color: 'bg-orange-50',
    department: "Women's Fashion",
  },
  {
    id: 'lehengas',
    title: 'Lehengas',
    handle: 'lehengas',
    image: U('1617627143750-d86bc21e42bb'),
    emoji: '🪡',
    description: 'Bridal & festive collections',
    color: 'bg-red-50',
    department: "Women's Fashion",
  },
  {
    id: 'womens-western',
    title: 'Western Wear',
    handle: 'western-wear',
    image: U('1434389677669-e08d4d19e19a'),
    emoji: '👖',
    description: 'Contemporary cuts and styles',
    color: 'bg-indigo-50',
    department: "Women's Fashion",
  },

  // ── Men's Fashion ───────────────────────────────────────────────────────────
  {
    id: 'mens-suits',
    title: 'Suits',
    handle: 'mens-suits',
    image: U('1507003211169-0a1dd7228f2d'),
    emoji: '🤵',
    description: 'Bespoke tailoring for the distinguished man',
    color: 'bg-slate-50',
    department: "Men's Fashion",
  },
  {
    id: 'mens-shirts',
    title: 'Shirts',
    handle: 'shirts',
    image: U('1596755094514-f87e34085b2c'),
    emoji: '👔',
    description: 'Premium fabrics, impeccable fit',
    color: 'bg-blue-50',
    department: "Men's Fashion",
  },
  {
    id: 'mens-kurtas',
    title: 'Ethnic Wear',
    handle: 'mens-ethnic',
    image: U('1583391265880-6a8a40b5e375'),
    emoji: '🧥',
    description: 'Sherwanis, kurtas & more',
    color: 'bg-yellow-50',
    department: "Men's Fashion",
  },
  {
    id: 'mens-casual',
    title: 'Casual Wear',
    handle: 'mens-casual',
    image: U('1542291026-7eec264c27ff'),
    emoji: '👕',
    description: 'Relaxed luxury for everyday life',
    color: 'bg-green-50',
    department: "Men's Fashion",
  },

  // ── Accessories ─────────────────────────────────────────────────────────────
  {
    id: 'handbags',
    title: 'Handbags',
    handle: 'handbags',
    image: U('1548036161-32ba7c80e79b'),
    emoji: '👜',
    description: 'Italian leather & artisan craft',
    color: 'bg-neutral-50',
    department: 'Accessories',
  },
  {
    id: 'watches',
    title: 'Watches',
    handle: 'watches',
    image: U('1523170335258-f87a2d362db2'),
    emoji: '⌚',
    description: 'Swiss precision, timeless design',
    color: 'bg-zinc-50',
    department: 'Accessories',
  },
  {
    id: 'jewellery',
    title: 'Jewellery',
    handle: 'jewellery',
    image: U('1515562141207-7a88fb7ce338'),
    emoji: '💎',
    description: 'Fine gold, silver & gemstones',
    color: 'bg-amber-50',
    department: 'Accessories',
  },
  {
    id: 'sunglasses',
    title: 'Sunglasses',
    handle: 'sunglasses',
    image: U('1572635196237-14b3f281503f'),
    emoji: '🕶️',
    description: 'Statement frames, UV protection',
    color: 'bg-gray-50',
    department: 'Accessories',
  },
  {
    id: 'belts',
    title: 'Belts',
    handle: 'belts',
    image: U('1553062407-98eeb64c6a62'),
    emoji: '👜',
    description: 'Full-grain leather essentials',
    color: 'bg-stone-50',
    department: 'Accessories',
  },
  {
    id: 'scarves',
    title: 'Scarves & Stoles',
    handle: 'scarves',
    image: U('1544551763-46a013bb70d5'),
    emoji: '🧣',
    description: 'Cashmere, silk & fine wool',
    color: 'bg-teal-50',
    department: 'Accessories',
  },

  // ── Footwear ─────────────────────────────────────────────────────────────────
  {
    id: 'heels',
    title: 'Heels',
    handle: 'heels',
    image: U('1543163521-1bf539c55dd2'),
    emoji: '👠',
    description: 'From stilettos to block heels',
    color: 'bg-rose-50',
    department: 'Footwear',
  },
  {
    id: 'sneakers',
    title: 'Sneakers',
    handle: 'sneakers',
    image: U('1542291026-7eec264c27ff'),
    emoji: '👟',
    description: 'Luxury casual footwear',
    color: 'bg-blue-50',
    department: 'Footwear',
  },
  {
    id: 'formal-shoes',
    title: 'Formal Shoes',
    handle: 'formal-shoes',
    image: U('1449505278314-329ae76890e3'),
    emoji: '👞',
    description: 'Oxford, derby & loafer styles',
    color: 'bg-stone-50',
    department: 'Footwear',
  },
  {
    id: 'sandals',
    title: 'Sandals',
    handle: 'sandals',
    image: U('1603487742131-4160cf36f79a'),
    emoji: '👡',
    description: 'Handcrafted leather sandals',
    color: 'bg-amber-50',
    department: 'Footwear',
  },

  // ── Beauty & Grooming ────────────────────────────────────────────────────────
  {
    id: 'skincare',
    title: 'Skincare',
    handle: 'skincare',
    image: U('1556228578-8c89e6adf883'),
    emoji: '✨',
    description: 'Clean beauty, radiant results',
    color: 'bg-pink-50',
    department: 'Beauty',
  },
  {
    id: 'fragrances',
    title: 'Fragrances',
    handle: 'fragrances',
    image: U('1541643600914-78b084683702'),
    emoji: '🌸',
    description: 'Niche perfumes & luxury scents',
    color: 'bg-purple-50',
    department: 'Beauty',
  },
  {
    id: 'haircare',
    title: 'Hair Care',
    handle: 'haircare',
    image: U('1522337360788-8b13dee7a37e'),
    emoji: '💆',
    description: 'Salon-grade hair essentials',
    color: 'bg-emerald-50',
    department: 'Beauty',
  },

  // ── Home & Lifestyle ─────────────────────────────────────────────────────────
  {
    id: 'home-decor',
    title: 'Home Décor',
    handle: 'home-decor',
    image: U('1555041469-a586c61ea9bc'),
    emoji: '🏡',
    description: 'Artisan pieces for refined spaces',
    color: 'bg-neutral-50',
    department: 'Home',
  },
  {
    id: 'candles',
    title: 'Candles & Aroma',
    handle: 'candles',
    image: U('1602523961358-f9f03dd557db'),
    emoji: '🕯️',
    description: 'Luxury hand-poured candles',
    color: 'bg-amber-50',
    department: 'Home',
  },
  {
    id: 'stationery',
    title: 'Stationery',
    handle: 'stationery',
    image: U('1456735190827-d1262f71b8a3'),
    emoji: '📓',
    description: 'Fine paper goods & writing instruments',
    color: 'bg-sky-50',
    department: 'Home',
  },
  {
    id: 'gifting',
    title: 'Gift Sets',
    handle: 'gift-sets',
    image: U('1513201099705-a9746bab22b3'),
    emoji: '🎁',
    description: 'Luxury gift curation for every occasion',
    color: 'bg-rose-50',
    department: 'Home',
  },
  {
    id: 'apparel',
    title: 'All Apparel',
    handle: 'apparel',
    image: U('1490481651871-ab68de25d43d'),
    emoji: '👗',
    description: 'The complete fashion archive',
    color: 'bg-neutral-50',
    department: 'Featured',
  },
  {
    id: 'accessories-all',
    title: 'All Accessories',
    handle: 'accessories',
    image: U('1584917865442-de89df76afd3'),
    emoji: '✨',
    description: 'Complete the look',
    color: 'bg-neutral-50',
    department: 'Featured',
  },
];
