/**
 * @file config/sampleProducts.ts
 * @description 20 Premium Sample Products for Testing
 * Use these as templates when importing real products to Shopify
 */

export const SAMPLE_PRODUCTS = [
  {
    id: '1',
    title: 'Premium Stainless Steel Water Bottle',
    price: 49.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1602143407151-7e36dd5f5ebe?w=500&h=500&fit=crop',
    category: 'Wellness',
    rating: 4.9,
    reviews: 234,
    description: 'Double-walled insulated bottle keeps drinks cold for 24 hours or hot for 12 hours. Perfect for fitness, work, or travel.',
    specs: ['25oz capacity', 'BPA-free', 'Eco-friendly', 'Lifetime warranty'],
    variants: ['Black', 'Silver', 'Gold', 'Rose Gold'],
    inStock: true,
    tags: ['bestseller', 'eco-friendly'],
  },
  {
    id: '2',
    title: 'Luxury Silk Pillowcase Set',
    price: 89.99,
    salePrice: 69.99,
    image: 'https://images.unsplash.com/photo-1615071422253-41e66d3f0b29?w=500&h=500&fit=crop',
    category: 'Sleep & Comfort',
    rating: 4.8,
    reviews: 567,
    description: 'Premium 100% mulberry silk pillowcases. Hypoallergenic, gentle on skin and hair.',
    specs: ['100% mulberry silk', 'Set of 2', 'Anti-wrinkle', 'Machine washable'],
    variants: ['Ivory', 'Champagne', 'Rose', 'White'],
    inStock: true,
    tags: ['bestseller', 'luxury'],
  },
  {
    id: '3',
    title: 'Professional Portable Espresso Machine',
    price: 199.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1559373584-fa4d409b3cde?w=500&h=500&fit=crop',
    category: 'Kitchen',
    rating: 4.7,
    reviews: 345,
    description: 'Compact espresso maker for perfect coffee anywhere. Takes 30 seconds to heat up.',
    specs: ['9-bar pressure', 'USB rechargeable', 'Compatible with any ground coffee', 'Includes travel case'],
    variants: ['Black', 'Silver', 'Titanium'],
    inStock: true,
    tags: ['gadget', 'premium'],
  },
  {
    id: '4',
    title: 'Organic Cotton Bath Towel Collection',
    price: 59.99,
    salePrice: 44.99,
    image: 'https://images.unsplash.com/photo-1621905167918-48416bd8575a?w=500&h=500&fit=crop',
    category: 'Home & Bath',
    rating: 4.9,
    reviews: 234,
    description: 'Luxurious organic cotton towels. Ultra-absorbent and soft, perfect for everyday use.',
    specs: ['100% organic cotton', 'Set of 4', 'Hypoallergenic', 'Sustainable'],
    variants: ['White', 'Gray', 'Charcoal', 'Navy'],
    inStock: true,
    tags: ['bestseller', 'eco-friendly'],
  },
  {
    id: '5',
    title: 'Wireless Noise-Cancelling Headphones',
    price: 299.99,
    salePrice: 249.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.8,
    reviews: 1200,
    description: 'Premium noise-cancelling headphones with 30-hour battery life and premium sound.',
    specs: ['Active noise cancellation', '30-hour battery', 'Premium audio', 'Bluetooth 5.0'],
    variants: ['Black', 'Silver', 'Gold'],
    inStock: true,
    tags: ['bestseller', 'tech'],
  },
  {
    id: '6',
    title: 'Aromatherapy Diffuser with Essential Oils',
    price: 79.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500&h=500&fit=crop',
    category: 'Wellness',
    rating: 4.7,
    reviews: 456,
    description: 'Ultrasonic diffuser with essential oil set. Creates calming atmosphere in any room.',
    specs: ['300ml capacity', 'Ultrasonic technology', 'Includes 5 essential oils', 'LED lights'],
    variants: ['White', 'Black', 'Rose Gold'],
    inStock: true,
    tags: ['wellness'],
  },
  {
    id: '7',
    title: 'Premium Yoga Mat with Carrying Strap',
    price: 69.99,
    salePrice: 49.99,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop',
    category: 'Fitness',
    rating: 4.9,
    reviews: 789,
    description: 'Non-slip yoga mat perfect for all fitness levels. Includes free carrying strap.',
    specs: ['6mm thickness', 'Non-slip surface', 'Eco-friendly TPE', 'Easy to clean'],
    variants: ['Navy', 'Purple', 'Sage Green', 'Black'],
    inStock: true,
    tags: ['bestseller', 'fitness'],
  },
  {
    id: '8',
    title: 'Stainless Steel Travel Food Container',
    price: 39.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=500&fit=crop',
    category: 'Travel',
    rating: 4.8,
    reviews: 345,
    description: 'Leak-proof lunch container. Keep meals hot or cold for hours.',
    specs: ['Stainless steel construction', 'Leak-proof design', 'Dishwasher safe', 'Three compartments'],
    variants: ['Silver', 'Navy', 'Black'],
    inStock: true,
    tags: ['travel', 'eco-friendly'],
  },
  {
    id: '9',
    title: 'Smart Home Temperature Controller',
    price: 149.99,
    salePrice: 119.99,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.6,
    reviews: 234,
    description: 'WiFi-enabled smart thermostat. Control temperature from anywhere.',
    specs: ['WiFi enabled', 'Mobile app control', 'Energy saving mode', 'Voice compatible'],
    variants: ['White', 'Black'],
    inStock: true,
    tags: ['tech', 'smart-home'],
  },
  {
    id: '10',
    title: 'Premium Leather Crossbody Bag',
    price: 129.99,
    salePrice: 99.99,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop',
    category: 'Fashion',
    rating: 4.9,
    reviews: 567,
    description: 'Genuine Italian leather crossbody bag. Perfect for daily use or travel.',
    specs: ['100% genuine leather', 'Italian crafted', 'RFID protection', 'Adjustable strap'],
    variants: ['Brown', 'Black', 'Cognac', 'Tan'],
    inStock: true,
    tags: ['bestseller', 'luxury', 'fashion'],
  },
  {
    id: '11',
    title: 'Bamboo Cutting Board Set',
    price: 54.99,
    salePrice: 39.99,
    image: 'https://images.unsplash.com/photo-1577720643272-265de9b2e1a8?w=500&h=500&fit=crop',
    category: 'Kitchen',
    rating: 4.8,
    reviews: 289,
    description: 'Eco-friendly bamboo cutting board set with knife included.',
    specs: ['Sustainable bamboo', 'Set of 3', 'Sharp chef knife included', 'Antibacterial'],
    variants: ['Natural'],
    inStock: true,
    tags: ['eco-friendly', 'kitchen'],
  },
  {
    id: '12',
    title: 'Ultra-Soft Cashmere Sweater',
    price: 189.99,
    salePrice: 149.99,
    image: 'https://images.unsplash.com/photo-1521527573588-7218cf4b465c?w=500&h=500&fit=crop',
    category: 'Fashion',
    rating: 4.9,
    reviews: 234,
    description: 'Premium 100% cashmere sweater. Luxuriously soft and warm.',
    specs: ['100% cashmere', 'Hand-stitched', 'Crewneck design', 'Multiple sizes'],
    variants: ['Black', 'Cream', 'Navy', 'Burgundy', 'Gray'],
    inStock: true,
    tags: ['bestseller', 'luxury', 'fashion'],
  },
  {
    id: '13',
    title: 'LED Ring Light with Stand',
    price: 69.99,
    salePrice: 49.99,
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.7,
    reviews: 456,
    description: 'Professional LED ring light for photography, streaming, and content creation.',
    specs: ['12-inch LED ring', 'Adjustable brightness', 'USB powered', 'Phone mount included'],
    variants: ['Black', 'White'],
    inStock: true,
    tags: ['tech', 'content-creation'],
  },
  {
    id: '14',
    title: 'Organic Bamboo Toothbrush Set',
    price: 24.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1607613814075-e51df1bdc82f?w=500&h=500&fit=crop',
    category: 'Wellness',
    rating: 4.8,
    reviews: 234,
    description: 'Eco-friendly bamboo toothbrushes made from sustainable sources.',
    specs: ['100% bamboo', 'Set of 4', 'Biodegradable', 'Soft bristles'],
    variants: ['Natural'],
    inStock: true,
    tags: ['eco-friendly', 'wellness'],
  },
  {
    id: '15',
    title: 'Smart Fitness Watch',
    price: 249.99,
    salePrice: 199.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.8,
    reviews: 678,
    description: 'Advanced fitness tracker with heart rate, sleep, and step monitoring.',
    specs: ['Heart rate monitor', 'Sleep tracking', '14-day battery', 'Water resistant'],
    variants: ['Black', 'Silver', 'Rose Gold'],
    inStock: true,
    tags: ['bestseller', 'tech', 'fitness'],
  },
  {
    id: '16',
    title: 'Weighted Blanket 15lbs',
    price: 119.99,
    salePrice: 89.99,
    image: 'https://images.unsplash.com/photo-1589519160732-57fc498494f8?w=500&h=500&fit=crop',
    category: 'Sleep & Comfort',
    rating: 4.9,
    reviews: 1000,
    description: 'Premium weighted blanket designed to improve sleep quality.',
    specs: ['15 lbs weight', '100% cotton', 'Non-toxic glass beads', 'Queen size'],
    variants: ['Gray', 'Navy', 'White'],
    inStock: true,
    tags: ['bestseller', 'wellness', 'sleep'],
  },
  {
    id: '17',
    title: 'Portable Phone Charger 20000mAh',
    price: 44.99,
    salePrice: 34.99,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500&h=500&fit=crop',
    category: 'Electronics',
    rating: 4.7,
    reviews: 456,
    description: 'Fast-charging portable battery with USB-C and lightning cables.',
    specs: ['20000 mAh capacity', 'Dual USB ports', 'Fast charging', 'Compact design'],
    variants: ['Black', 'White', 'Rose Gold'],
    inStock: true,
    tags: ['tech', 'travel'],
  },
  {
    id: '18',
    title: 'Premium Air Purifier',
    price: 299.99,
    salePrice: 249.99,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500&h=500&fit=crop',
    category: 'Home & Health',
    rating: 4.8,
    reviews: 345,
    description: 'HEPA filter air purifier for clean air in your home.',
    specs: ['HEPA filter', 'Smart mode', 'Whisper quiet', 'Covers 500 sq ft'],
    variants: ['White', 'Black'],
    inStock: true,
    tags: ['wellness', 'smart-home'],
  },
  {
    id: '19',
    title: 'Stainless Steel Coffee Grinder',
    price: 89.99,
    salePrice: 69.99,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=500&h=500&fit=crop',
    category: 'Kitchen',
    rating: 4.7,
    reviews: 234,
    description: 'Burr coffee grinder for perfectly ground beans every time.',
    specs: ['Burr grinding', '17 grind settings', 'Stainless steel', 'Quiet operation'],
    variants: ['Silver', 'Black'],
    inStock: true,
    tags: ['kitchen', 'premium'],
  },
  {
    id: '20',
    title: 'Premium Sunglasses Collection',
    price: 149.99,
    salePrice: 119.99,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop',
    category: 'Fashion',
    rating: 4.8,
    reviews: 567,
    description: 'UV-protected designer sunglasses with polarized lenses.',
    specs: ['100% UV protection', 'Polarized lenses', 'Premium materials', 'Lifetime warranty'],
    variants: ['Black', 'Brown', 'Gold', 'Silver'],
    inStock: true,
    tags: ['bestseller', 'fashion', 'luxury'],
  },
];

// Helper function to get products by category
export function getProductsByCategory(category: string) {
  return SAMPLE_PRODUCTS.filter(p => p.category === category);
}

// Helper function to get bestsellers
export function getBestsellers() {
  return SAMPLE_PRODUCTS.filter(p => p.tags.includes('bestseller')).slice(0, 10);
}

// Helper function to get on-sale products
export function getOnSaleProducts() {
  return SAMPLE_PRODUCTS.filter(p => p.salePrice !== null);
}
